### PR TITLE
Purging gradient style from app

### PR DESCRIPTION
**Pull request by jessikra**
Removed linear gradient from entire app across 12 files. Only remaining place is Profile.js where some override is causing the background to be black once gradient component is removed.

### CODE REVIEW

**Review by Danny393 — APPROVED** [review]
Looks good, just be sure to explain and show how .vscode/launch.json file works with VS Code and how to use it effectively in next Stand Up

**Review by OAKevin — APPROVED** [review]
Ignore comment its working fine when i tried on my laptop

**Comment by jessikra** [comment]
> Looks good, just be sure to explain and show how .vscode/launch.json file works with VS Code and how to use it effectively in next Stand Up

Yes this can be removed or added, this file does not affect functionality of project at all, it's just a config file for VSCode where we can specify certain settings for vscode when opening this project. Planning on adding prettier package here for example.

**Comment by jessikra** [comment]
Attached a screenshot of the profile view to state that background is no longer black with latest
photo_2021-10-06 19 57 55

**Pull request merged**
